// Case charts use reported figures; any normalisation is labelled explicitly.
function caseChart(c){
 let title,caption,unit,max,rows,kind=t('REPORTED HISTORICAL DATA','已報告的歷史數據');
 if(c.id==='ltcm'){
  title=t('What a 44% loss leaves behind','虧損44%後，剩下多少？');unit=t('Capital index','資本指數');max=100;kind=t('NORMALISED FROM A REPORTED LOSS','按已報告虧損作標準化計算');
  rows=[{label:t('Before August','8月前'),value:100,note:t('Starting capital is set to 100 for comparison; this is not a dollar amount.','期初資本設為100以便比較，並非美元金額。')},{label:t('After August','8月後'),value:56,note:t('A reported 44% August loss leaves 56 out of the starting 100. This chart does not show the path within the month.','已報告的8月虧損44%，令期初100剩下56。此圖沒有顯示月內走勢。')}];
  caption=t('August 1998. Before = 100; after = 100 × (1 − 0.44). This shows the reported fund-value decline, not a complete account of cash or margin requirements.','1998年8月。期初＝100；期末＝100×（1−0.44）。這顯示已報告的基金價值跌幅，並非現金或保證金要求的完整紀錄。');
 }else if(c.id==='replication'){
  title=t('Count all 100 replication attempts','把100次重複驗證全部計算在內');unit=t('Studies','研究項目');max=100;
  rows=[{label:t('Met criterion','達到標準'),value:36,note:t('36% met the criterion: statistical significance in the same direction as the original finding.','36%達到標準：在與原發現相同方向上有統計顯著結果。')},{label:t('Did not meet it','未達標準'),value:64,note:t('The other 64% did not meet this particular criterion. That is not equivalent to proving 64 original findings false.','其餘64%未達這項特定標準，並不等於證明64項原發現錯誤。')}];
  caption=t('100 attempts; 36% met the stated significance-and-direction criterion. The remaining count is calculated as 100 − 36. “Not meeting” this criterion is not a fraud finding.','100次嘗試，36%達到指定顯著程度與方向標準。其餘數目按100−36計算。未達標不代表造假。');
 }else if(c.id==='buffett'){
  title=t('The ten-year wager: final gains','十年賭約：最終累積收益');unit=t('Cumulative gain (%)','累積收益（%）');max=150;
  rows=[['A',21.7],['B',42.3],['C',87.7],['D*',2.8],['E',27.0]].map(([name,value])=>({label:t('Fund '+name,'基金'+name),value,note:t(`Fund-of-funds ${name}: ${value.toFixed(1)}% final gain in Buffett’s reported table. The letter does not publicly identify the funds.`,`基金中的基金${name}：巴菲特報表記錄最終收益${value.toFixed(1)}%。股東信沒有公開基金名稱。`)}));
  rows.push({label:t('Index fund','指數基金'),value:125.8,note:t('The S&P 500 index fund gained 125.8% over the wager. This is a cumulative gain, not an annual return.','標普500指數基金在賭約期內累積收益125.8%。這是累積收益，不是每年回報。')});
  caption=t('2008–2017, as reported in Berkshire Hathaway’s 2017 letter. *Fund D was liquidated in 2017; its reported result reflects its operation. This selected comparison is not a forecast.','2008至2017年，資料來自巴郡2017年股東信。*基金D於2017年清算，報告結果反映其營運期間。此選定比較並非預測。');
 }else if(c.id==='deepblue'){
  title=t('Two matches. A different winner.','兩次對賽，不同贏家。');unit=t('Match points (out of 6)','對賽得分（滿分6分）');max=6;
  rows=[{label:t('1996 · Kasparov','1996・卡斯帕羅夫'),value:4,note:t('Kasparov won the 1996 match 4–2 after Deep Blue won the opening game.','深藍贏首局後，卡斯帕羅夫以4比2贏得1996年對賽。')},{label:t('1996 · Deep Blue','1996・深藍'),value:2,note:t('Deep Blue scored 2 points in the first six-game match.','深藍在首次六局對賽取得2分。')},{label:t('1997 · Kasparov','1997・卡斯帕羅夫'),value:2.5,note:t('In the rematch, Kasparov scored 2.5 points. Drawn games give each player half a point.','重賽中，卡斯帕羅夫取得2.5分。和局雙方各得半分。')},{label:t('1997 · Deep Blue','1997・深藍'),value:3.5,note:t('After improvements, Deep Blue won the rematch 3.5–2.5. The result measures chess performance in these matches.','改善後，深藍以3.5比2.5勝出重賽。此結果量度這兩場國際象棋對賽表現。')}];
  caption=t('IBM’s match history. Each six-game match totals six points across both players; a draw contributes half a point to each. These are final scores, not a game-by-game time series.','IBM對賽歷史。每場六局對賽雙方合計六分，和局各得半分。這是最終比分，不是逐局時間序列。');
 }else return '';
 const fmt=v=>c.id==='buffett'?v.toFixed(1)+'%':String(v);
 return `<figure class="case-chart" aria-labelledby="case-chart-title"><div class="chart-heading"><span class="label">${kind}</span><h3 id="case-chart-title">${title}</h3><p>${t('Select a bar to explore what the number means.','選一條柱，看看數字代表甚麼。')}</p></div><div class="case-bars" role="group" aria-label="${esc(title)}">${rows.map((r,i)=>`<button type="button" class="case-bar ${c.id==='buffett'&&i===5?'benchmark':''}" data-chart-note="${esc(r.note)}" aria-pressed="false" aria-label="${esc(r.label)}: ${fmt(r.value)}"><span class="bar-name">${esc(r.label)}</span><span class="bar-track"><span class="bar-fill" style="width:${r.value/max*100}%"></span></span><strong class="bar-value">${fmt(r.value)}</strong></button>`).join('')}<div class="bar-axis"><span>0</span><span>${max/2}</span><span>${max}</span></div><p class="bar-unit">${unit}</p></div><p class="chart-note" role="status" aria-live="polite">${t('Compare the scale and the denominator before drawing a conclusion.','下結論前，先比較刻度與分母。')}</p><figcaption>${caption} <a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${t('Source','來源')} ↗</a></figcaption><details class="chart-data"><summary>${t('View the data table','查看數據表')}</summary><table><thead><tr><th scope="col">${t('Observation','觀察項目')}</th><th scope="col">${unit}</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${esc(r.label)}</th><td>${fmt(r.value)}</td></tr>`).join('')}</tbody></table></details></figure>`;
}
function initCaseCharts(){main.querySelectorAll('.case-bar').forEach(b=>b.onclick=()=>{const chart=b.closest('.case-chart');chart.querySelectorAll('.case-bar').forEach(x=>x.setAttribute('aria-pressed',x===b));chart.querySelector('.chart-note').textContent=b.dataset.chartNote;});}
