// Interactive learning tools: illustrative calculations, never historical returns.
let moduleFilter=0,readingFilter='all';
const collapsedModules=new Set();
let featuredCase=0;
const money=n=>new Intl.NumberFormat(lang==='zh-HK'?'zh-HK':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
function labMarkup(mode='risk',compact=false){
 const tabs=[['risk',t('Risk & survival','風險與生存')],['odds',t('Odds & payoffs','概率與回報')],['evidence',t('Count the evidence','計算證據')]];
 return `<div class="learning-lab ${compact?'compact':''}"><div class="lab-heading"><div><p class="eyebrow">${t('THE LEARNING LAB','學習實驗室')}</p><h2>${t('Move a slider. Change your perspective.','移動滑桿，換個角度思考。')}</h2></div><span class="lab-badge">${t('TRY IT','試一試')} ↗</span></div><div class="lab-tabs" role="tablist" aria-label="${t('Learning experiments','學習實驗')}">${tabs.map(([id,name])=>`<button type="button" role="tab" id="tab-${id}" aria-controls="lab-panel" aria-selected="${id===mode}" tabindex="${id===mode?0:-1}" data-lab="${id}">${name}</button>`).join('')}</div><div id="lab-panel" role="tabpanel" aria-labelledby="tab-${mode}"></div><p class="lab-footnote">${t('Illustrative assumptions, not a market forecast. Change one input at a time and explain what changed.','假設計算，並非市場預測。每次改一個輸入，再解釋結果為何改變。')}</p></div>`;
}
function initLab(host,mode='risk'){
 host.innerHTML=labMarkup(mode,host.dataset.compact==='true');
 const buttons=[...host.querySelectorAll('[data-lab]')];
 buttons.forEach((b,i)=>{
  b.onclick=()=>{buttons.forEach(x=>{const on=x===b;x.setAttribute('aria-selected',on);x.tabIndex=on?0:-1;});const panel=host.querySelector('#lab-panel');panel.setAttribute('aria-labelledby',b.id);labPanel(panel,b.dataset.lab);};
  b.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;buttons[n].click();buttons[n].focus();}};
 });
 labPanel(host.querySelector('#lab-panel'),mode);
}
function range(id,label,min,max,value,step=1,suffix=''){return `<label class="range-control" for="${id}"><span>${label}<output id="${id}-value" for="${id}">${value}${suffix}</output></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-suffix="${suffix}"></label>`;}
function labPanel(panel,mode){
 const risk=mode==='risk',odds=mode==='odds';
 let controls=risk?range('lab-leverage',t('Exposure / capital','持倉／資本'),1,20,5,1,'×')+range('lab-move',t('Adverse price move','不利價格變動'),0,25,5,.5,'%'):odds?range('lab-win',t('Win probability','勝出概率'),10,90,80,1,'%')+range('lab-gain',t('Gain on a win','每次勝出的收益'),1,10,1,.5)+range('lab-loss',t('Loss on a loss','每次失敗的虧損'),1,20,5,.5)+range('lab-cost',t('Cost per attempt','每次成本'),0,1,0,.05):range('lab-total',t('Eligible observations','合資格觀察總數'),1,200,10)+range('lab-hits',t('Favourable outcomes','有利結果'),0,10,8);
 panel.innerHTML=`<div class="lab-layout"><div class="lab-controls"><h3>${risk?t('Can the position survive?','持倉能否生存？'):odds?t('Does a high win rate pay?','高勝率一定有回報嗎？'):t('What is the missing denominator?','缺少的分母是甚麼？')}</h3><p>${risk?t('Start with $10,000 of capital. Explore the effect of exposure and a move against you.','以10,000美元資本開始，探索持倉及不利波動的影響。'):odds?t('Keep the win rate high, then change the size of a loss. Watch the average payoff.','保持高勝率，再改變虧損大小，觀察平均回報。'):t('Keep eight favourable outcomes. Compare eight out of ten with eight out of forty.','保留八個有利結果，比較十次中八次與四十次中八次。')}</p>${controls}<button class="lab-reset" type="button">${t('Reset experiment','重設實驗')} ↺</button>${!risk?`<button class="lab-preset" type="button">${odds?t('Try a different payoff','試另一組回報'):t('Try 8 out of 40','試四十次中八次')} →</button>`:''}</div><div class="lab-result"><span class="label">${risk?t('CAPITAL REMAINING','剩餘資本'):odds?t('EXPECTED NET PAYOFF','預期淨回報'):t('OBSERVED SUCCESS RATE','觀察成功率')}</span><strong class="lab-number" id="lab-number"></strong><div class="lab-chart" id="lab-chart"></div><p class="lab-equation" id="lab-equation"></p><p id="lab-message" role="status" aria-live="polite"></p></div></div>`;
 const $=id=>panel.querySelector('#'+id),v=id=>Number($(id).value);
 const update=()=>{
  if(mode==='evidence'){ $('lab-hits').max=String(v('lab-total'));if(v('lab-hits')>v('lab-total'))$('lab-hits').value=String(v('lab-total')); }
  panel.querySelectorAll('input').forEach(x=>$(x.id+'-value').textContent=x.value+x.dataset.suffix);
  let number,equation,message,bars,negative=false;
  if(risk){const leverage=v('lab-leverage'),move=v('lab-move'),loss=10000*leverage*move/100,left=10000-loss;negative=left<=0;number=money(left);equation=`${money(10000)} − (${money(10000)} × ${leverage} × ${move}%)`;message=left<=0?t('The assumed loss uses all capital or more. A later rebound cannot restore a position already forced out.','假設損失已用盡或超過資本。已被迫離場的持倉，不能受惠於後來反彈。'):t(`The move consumes ${(loss/100).toFixed(1)}% of starting capital. Funding or margin constraints could force an exit sooner.`,`波動消耗期初資本的${(loss/100).toFixed(1)}%。融資或保證金限制可能更早迫使離場。`);bars=[[t('Remaining','剩餘'),Math.max(0,left)/100,'teal'],[t('Lost','損失'),Math.min(100,loss/100),'clay']];}
  else if(odds){const p=v('lab-win')/100,g=v('lab-gain'),l=v('lab-loss'),c=v('lab-cost'),ev=p*g-(1-p)*l-c;negative=ev<0;number=money(ev);equation=`${p.toFixed(2)} × $${g} − ${(1-p).toFixed(2)} × $${l} − $${c}`;message=ev>0?t('Positive under these assumptions, but an estimate is not a guarantee. Check the probabilities and costs.','在這些假設下為正，但估計並非保證。仍要檢查概率與成本。'):t('Frequent wins can coexist with a negative average payoff. The size of losses and costs matter.','經常勝出也可能有負的平均回報。虧損大小與成本都很重要。');bars=[[t('Win probability','勝出概率'),p*100,'teal'],[t('Loss probability','失敗概率'),(1-p)*100,'clay']];}
  else{const n=v('lab-total'),h=v('lab-hits'),pct=h/n*100;number=pct.toFixed(1)+'%';equation=`${h} / ${n} × 100`;message=t('This describes the chosen sample. It does not establish causation, a future probability or profit.','這只描述所選樣本，不能確立因果、未來概率或利潤。');bars=[[t('Favourable','有利'),pct,'teal'],[t('Other outcomes','其他結果'),100-pct,'clay']];}
  $('lab-number').textContent=number;$('lab-number').classList.toggle('negative',negative);$('lab-equation').textContent=equation;$('lab-message').textContent=message;
  $('lab-chart').innerHTML=bars.map(([label,value,color])=>`<div class="chart-row"><span>${label}</span><strong>${value.toFixed(1)}%</strong><div class="chart-track"><span class="${color}" style="width:${value}%"></span></div></div>`).join('');
 };
 panel.querySelectorAll('input').forEach(x=>x.oninput=update);panel.querySelector('.lab-reset').onclick=()=>labPanel(panel,mode);
 const preset=panel.querySelector('.lab-preset');if(preset)preset.onclick=()=>{if(odds){$('lab-win').value=55;$('lab-gain').value=2;$('lab-loss').value=1;$('lab-cost').value=.1;}else{$('lab-total').value=40;$('lab-hits').max=40;$('lab-hits').value=8;}update();};update();
}
function labPage(){main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">${t('LEARN BY DOING','在實踐中學習')}</p><h1>${t('Make the invisible visible.','讓看不見的關係變得清晰。')}</h1><p>${t('Three small experiments in risk, probability and evidence. No account, no real trades.','三個關於風險、概率與證據的小實驗。不需帳戶，也沒有真實交易。')}</p></div></div><div id="standalone-lab"></div><a class="text-link" href="#courses">← ${t('Back to your learning path','返回學習路徑')}</a>`;initLab(document.getElementById('standalone-lab'));}
function enhanceHome(){
 const hero=main.querySelector('.hero');hero.querySelector('.hero-index').outerHTML=`<div class="hero-art" aria-hidden="true"><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><div class="art-book"><span>VICTOR<br>NIEDERHOFFER</span><strong>${t('THE EDUCATION<br>OF A SPECULATOR','投機<br>生涯')}</strong><div class="book-rule"></div><small>${t('A FIELD GUIDE TO THINKING','思考的實地指南')}</small><svg viewBox="0 0 240 90"><path d="M0 70L25 60L40 65L60 42L78 54L105 20L125 45L150 30L172 50L197 15L218 25L240 0" fill="none" stroke="currentColor" stroke-width="2"/></svg></div><div class="art-note">${t('Curiosity is the edge.','好奇心，是起點。')}<span>01 / 48</span></div></div>`;
 const heading=main.querySelector('.section-heading');heading.id='learning-path';
 heading.insertAdjacentHTML('afterend',`<div class="course-controls"><div class="module-filters" aria-label="${t('Filter modules','篩選單元')}"><button data-module="0" type="button">${t('All modules','所有單元')}</button>${DATA.modules.map(m=>`<button type="button" data-module="${m.id}">${String(m.id).padStart(2,'0')} ${esc(m.title)}</button>`).join('')}</div><div class="reading-filters" aria-label="${t('Filter reading status','篩選閱讀狀態')}">${[['all',t('All lessons','全部課程')],['unread',t('To read','待讀')],['done',t('Completed','已完成')]].map(([id,name])=>`<button type="button" data-reading="${id}">${name}</button>`).join('')}<span id="lesson-count" role="status"></span></div></div>`);
 const refresh=()=>{document.querySelectorAll('[data-module]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.module)===moduleFilter));document.querySelectorAll('[data-reading]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.reading===readingFilter));cards(document.getElementById('lesson-search').value);};
 main.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{moduleFilter=Number(b.dataset.module);refresh();});main.querySelectorAll('[data-reading]').forEach(b=>b.onclick=()=>{readingFilter=b.dataset.reading;refresh();});refresh();
 main.querySelector('.progress-panel').insertAdjacentHTML('beforebegin',`<section class="featured-case"><div class="feature-intro"><p class="eyebrow">${t('FROM IDEA TO REALITY','從想法走到現實')}</p><h2>${t('One event.<br>Many lessons.','一個事件。<br>多種啟示。')}</h2><p>${t('Explore the moments that put a theory to the test.','探索考驗理論的真實時刻。')}</p><div class="feature-controls"><button type="button" id="case-prev" aria-label="${t('Previous case','上一案例')}">←</button><span id="case-position"></span><button type="button" id="case-next" aria-label="${t('Next case','下一案例')}">→</button></div></div><div id="featured-content" aria-live="polite"></div></section>`);
 function feature(){const c=DATA.cases[featuredCase],l=DATA.lessons.find(l=>l.case.id===c.id);document.getElementById('case-position').textContent=String(featuredCase+1).padStart(2,'0')+' / '+DATA.cases.length;document.getElementById('featured-content').innerHTML=`<span class="feature-date">${esc(c.date)}</span><h3>${esc(c.title)}</h3><p>${esc(c.facts)}</p><div class="feature-bottom"><a class="text-link" href="#lesson/${l.id}">${t('Explore this case','探索此案例')} <span>↗</span></a><a class="source-link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${t('Original source','原始來源')} ↗</a></div>`;}
 document.getElementById('case-prev').onclick=()=>{featuredCase=(featuredCase+DATA.cases.length-1)%DATA.cases.length;feature();};document.getElementById('case-next').onclick=()=>{featuredCase=(featuredCase+1)%DATA.cases.length;feature();};feature();
 main.insertAdjacentHTML('beforeend','<section id="home-lab" class="home-lab"></section>');initLab(document.getElementById('home-lab'));
}
function enhanceCards(){
 const grid=document.getElementById('course-grid');if(!grid)return;
 const count=grid.querySelectorAll('.lesson-list li').length,counter=document.getElementById('lesson-count');if(counter)counter.textContent=`${count} ${t('lessons','課')}`;
 grid.querySelectorAll('.chapter-card').forEach(card=>{
  const first=card.querySelector('.lesson-num').textContent,m=Number(first.split('-')[0]),done=DATA.lessons.filter(l=>l.module===m&&state.done.includes(l.id)).length;
  card.style.setProperty('--module-hue',[155,25,215,40,280,170,5,200][m-1]);
  card.querySelector('.chapter-top').insertAdjacentHTML('beforeend',`<button class="module-toggle" type="button" aria-expanded="${!collapsedModules.has(m)}" aria-label="${t('Show or hide lessons in','顯示或隱藏課程：')} ${esc(DATA.modules[m-1].title)}">${collapsedModules.has(m)?'+':'−'}</button>`);
  card.insertAdjacentHTML('beforeend',`<div class="module-completion"><span>${done}/6 ${t('complete','已完成')}</span><div><i style="width:${done/6*100}%"></i></div></div>`);
  const ul=card.querySelector('.lesson-list');ul.id='module-lessons-'+m;ul.hidden=collapsedModules.has(m);const b=card.querySelector('.module-toggle');b.setAttribute('aria-controls',ul.id);b.onclick=()=>{ul.hidden=!ul.hidden;b.textContent=ul.hidden?'+':'−';b.setAttribute('aria-expanded',!ul.hidden);if(ul.hidden)collapsedModules.add(m);else collapsedModules.delete(m);};
 });
}
function enhanceLesson(id){
 const l=DATA.lessons.find(l=>l.id===id);if(!l)return;
 main.querySelectorAll('.lesson-sidebar a').forEach(a=>{if(a.hash==='#lesson/'+id){a.classList.add('current');a.setAttribute('aria-current','page');}});
 const mode=({1:'risk',2:'evidence',3:'odds',4:'odds',5:'evidence',6:'risk',7:'odds',8:'evidence'})[l.module];
 main.querySelector('.task').insertAdjacentHTML('beforebegin',`<section class="lesson-experiment"><div class="experiment-launch"><div><span class="label">${t('PUT THE IDEA TO WORK','把想法付諸實踐')}</span><h2>${t('Try a small experiment','試一個小實驗')}</h2><p>${t('Explore a simplified model connected to this module.','探索與本單元相關的簡化模型。')}</p></div><button class="btn light" type="button" id="open-experiment" aria-expanded="false" aria-controls="lesson-lab">${t('Open experiment','開啟實驗')} ↗</button></div><div id="lesson-lab" data-compact="true" hidden></div></section>`);
 const launch=document.getElementById('open-experiment'),host=document.getElementById('lesson-lab');launch.onclick=()=>{const open=host.hidden;host.hidden=!open;launch.setAttribute('aria-expanded',open);launch.textContent=open?t('Close experiment ↑','關閉實驗 ↑'):t('Open experiment ↗','開啟實驗 ↗');if(open&&!host.innerHTML)initLab(host,mode);};
 main.querySelector('.quiz').insertAdjacentHTML('afterend',`<section class="reflection-journal"><span class="label">${t('YOUR FIELD NOTES','你的思考筆記')}</span><h2>${t('What changed your mind?','甚麼改變了你的想法？')}</h2><p>${esc(l.case.prompt)}</p><label for="lesson-note">${t('Your reflection · saved only in this browser','你的反思・只儲存在此瀏覽器')}</label><textarea id="lesson-note" rows="4" maxlength="4000" placeholder="${t('One observation, one assumption, one next question…','一項觀察、一個假設、一個下一步問題……')}"></textarea><div class="journal-status"><span id="note-status" role="status"></span><span id="note-count"></span></div></section>`);
 const note=document.getElementById('lesson-note'),status=document.getElementById('note-status'),key='speculator-note-'+id;
 try{note.value=localStorage.getItem(key)||'';}catch{status.textContent=t('Browser storage is unavailable.','瀏覽器儲存功能不可用。');}
 const count=()=>document.getElementById('note-count').textContent=note.value.length+' / 4000';count();
 note.oninput=()=>{count();try{if(note.value)localStorage.setItem(key,note.value);else localStorage.removeItem(key);status.textContent=t('Saved in this browser ✓','已儲存在此瀏覽器 ✓');}catch{status.textContent=t('Could not save. Keep a separate copy of your note.','未能儲存，請另外保留筆記。');}};
}
