// Conceptual AI illustrations accompany cases; they are not historical evidence.
const ART={ltcm:['A fragile bridge of financial paper above a chasm','金融文件搭成的脆弱橋樑，跨越深谷'],snb:['An alpine river crosses a broken policy boundary','阿爾卑斯河流穿過斷裂的政策界線'],knight:['Order tiles escape a trading console beside an emergency switch','交易指令從控制台湧出，旁邊有緊急停止掣'],replication:['Two research desks repeat and compare experiments','兩張研究桌重複並比較實驗'],deepblue:['Human and machine chess pieces face each other','人類與電腦棋子在棋盤上對峙'],buffett:['A simple growing path beside a path with repeated toll gates','簡單成長路徑與設有多重收費關卡的路徑'],house:['Dice, probability counters and a balance show recurring costs','骰子、概率計數器及天秤呈現重複成本'],flash:['A market skyline breaks as a narrow liquidity bridge disappears','市場剪影斷裂，狹窄的流動性橋樑消失'],gme:['A network connects a market’s different participants','網絡連接市場不同參與者'],challenger:['An engineering workshop with a shuttle model and inspection notebook','工程工作室內的穿梭機模型及檢查筆記'],spiva:['A research archive keeps missing folders visible','研究檔案室保留缺失資料夾的位置']};
Object.assign(ART,CHAPTER_ART);
const MODULE_ART={1:'ltcm',2:'replication',3:'deepblue',4:'house',5:'flash',6:'gme',7:'challenger',8:'spiva'};
function artImage(id,cls='',lazy=true){return `<img class="${cls}" src="assets/art/${id}.webp" alt="${esc(t(...ART[id]))}" width="1536" height="1024" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`;}
function artFigure(id,cls='',lazy=true){return `<figure class="visual-figure ${cls}">${artImage(id,'',lazy)}<figcaption>${t('AI-generated conceptual illustration · not a historical photograph','AI生成概念插畫・並非歷史照片')}</figcaption></figure>`;}
const DECISIONS={
1:{q:['Your model still looks right, but the lender wants cash tomorrow. What needs checking first?','模型仍然看似正確，但貸款方要求明天補現金。首先要檢查甚麼？'],options:[['Whether the position can survive the cash deadline','持倉能否撐過現金期限'],['Whether the original forecast sounded convincing','最初預測是否令人信服'],['Whether other traders agree with you','其他交易者是否同意你']],answer:0,why:['Funding deadlines can force an exit before a thesis has time to work. A model of value also needs a model of survival.','融資期限可能迫使你在論點得到驗證前離場。估值模型也需要生存模型。']},
2:{q:['A celebrated rule worked in the examples someone selected. What would strengthen the claim?','一項著名規則在某人挑選的例子中有效。甚麼能加強這項主張？'],options:[['A more confident explanation','更有信心的解釋'],['A defined test that includes failures and fresh data','明確測試，包含失敗例子及新資料'],['Another quotation from an expert','另一句專家名言']],answer:1,why:['Define the rule and comparison before counting. Include misses and examine data that did not shape the rule.','計數前先定義規則及比較基準。計入失敗例子，並檢查未用作制定規則的資料。']},
3:{q:['An opponent changes their approach halfway through the match. What is the useful response?','對手在比賽中途改變方法。甚麼回應較有用？'],options:[['Repeat the opening plan regardless','不論情況都重複開局計劃'],['Assume their change is a mistake','假設對方改變是犯錯'],['Reassess the position and test an adjustment','重新評估局面並測試調整']],answer:2,why:['A plan depends on the current rules, position and opponent. Feedback tells you when its assumptions need revision.','計劃取決於當前規則、局面及對手。回饋可指出何時需要修訂假設。']},
4:{q:['A game wins often, but each loss is large and every round has a fee. What should you calculate?','遊戲經常贏，但每次輸得多，而且每局收費。應計算甚麼？'],options:[['Expected net payoff, including losses and costs','計及虧損和成本的預期淨收益'],['Only the number of winning rounds','只計勝出局數'],['The largest possible prize','最大可能獎金']],answer:0,why:['Frequency, payoff size and costs all matter. A high win rate alone cannot tell you whether the average net payoff is positive.','頻率、收益幅度及成本都重要。單靠高勝率不能判斷平均淨收益是否為正。']},
5:{q:['A price chart resembles a famous past reversal. What is still missing?','價格圖表看似著名的歷史反轉。還欠甚麼？'],options:[['A dramatic name for the pattern','模式的戲劇性名稱'],['A defined rule, comparison and evidence beyond the selected picture','明確規則、比較及所選圖片以外的證據'],['A prediction with more decimal places','更多小數位的預測']],answer:1,why:['A resemblance generates a hypothesis. It does not establish the frequency, timing or profitability of the next move.','相似之處可產生假設，不能確立下一步的頻率、時間或盈利能力。']},
6:{q:['Two market series move together. What should you investigate before inferring a link?','兩組市場數據一起移動。推斷關係前應研究甚麼？'],options:[['Whether the lines use matching colours','線條是否使用相同顏色'],['Whether the relationship has a catchy label','關係是否有吸引的名稱'],['A mechanism, shared causes and changes in participants','機制、共同原因及參與者的變化']],answer:2,why:['Co-movement can have several explanations. Study who is acting, what connects the markets and whether conditions have changed.','共同移動可有多種解釋。研究誰在行動、甚麼連接市場，以及條件是否改變。']},
7:{q:['After a frustrating loss, you feel certain the next attempt must recover it. What deserves attention?','一次令人沮喪的虧損後，你確信下一次必定追回。甚麼值得留意？'],options:[['Whether emotion is replacing the evidence for the next decision','情緒是否取代下一步決定所需的證據'],['How quickly you can repeat the attempt','能多快重複嘗試'],['Who can be blamed for the last loss','上次虧損可歸咎於誰']],answer:0,why:['The next decision needs its own evidence. Frustration and a desire to recover are feelings, not a change in the odds.','下一步決定需要本身的證據。沮喪及追回損失的渴望是感受，不代表概率改變。']},
8:{q:['Your research file contains only funds that still exist. What could improve the comparison?','研究檔案只包含仍存在的基金。怎樣改善比較？'],options:[['Remove the weakest remaining funds','移除餘下最弱的基金'],['Account for closed funds and define the original sample','計入已關閉基金並定義原始樣本'],['Show only the best year','只展示最好的一年']],answer:1,why:['Surviving observations can give an incomplete picture. Define the denominator and investigate what disappeared before judging results.','存活的觀察項目可能呈現不完整圖像。評價結果前，先定義分母並研究消失的項目。']}
};
function decisionRoom(l){const d=DECISIONS[l.module];return `<section class="decision-room" aria-labelledby="decision-title"><div class="decision-intro"><span class="label">${t('YOUR MOVE · HYPOTHETICAL SCENARIO','到你決定・假設情境')}</span><h2 id="decision-title">${t('What would you do?','你會怎樣做？')}</h2><p>${esc(t(...d.q))}</p></div><div class="decision-options">${d.options.map((o,i)=>`<button type="button" class="decision-option" data-decision="${i}" aria-pressed="false"><span>${'ABC'[i]}</span>${esc(t(...o))}</button>`).join('')}</div><p class="decision-feedback" role="status" hidden></p></section>`;}
function initDecision(l){const d=DECISIONS[l.module];main.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{main.querySelectorAll('[data-decision]').forEach(x=>{x.setAttribute('aria-pressed',x===b);x.classList.remove('chosen-good','chosen-rethink');});const ok=Number(b.dataset.decision)===d.answer;b.classList.add(ok?'chosen-good':'chosen-rethink');const f=main.querySelector('.decision-feedback');f.hidden=false;f.textContent=(ok?t('A useful starting point. ','有用的起點。'):t('Consider the missing constraint. ','想想缺少了甚麼限制。'))+t(...d.why);});}
function takeawayDeck(l){return `<section class="takeaway-deck"><div class="section-heading"><div><span class="label">${t('PAUSE & RECALL','停一停・回想一下')}</span><h2>${t('Three ideas to keep','三個要點')}</h2><p>${t('Try to name an idea, then turn a card to check it.','先試說出一個要點，再翻卡核對。')}</p></div></div><div class="recall-grid">${l.takeaway.map((s,i)=>`<button class="recall-card" type="button" aria-expanded="false" aria-controls="recall-${i}"><span class="recall-number">0${i+1}</span><span class="recall-prompt">${t('Reveal an idea ↗','揭示要點 ↗')}</span><span class="recall-answer" id="recall-${i}" hidden>${esc(s)}</span></button>`).join('')}</div></section>`;}
function enhanceVisualLesson(l){const header=main.querySelector('.lesson-header');header.insertAdjacentHTML('beforeend',`<a class="editorial-byline" href="#about">${t('Speculator’s Library · Independent study edition','投機生涯資料庫・獨立學習版')}</a>`);header.querySelector('.desc').insertAdjacentHTML('afterend',artFigure('chapter-'+lessonChapter(l),'lesson-visual',false));header.insertAdjacentHTML('afterend',decisionRoom(l));main.querySelector('.lesson-visual figcaption').insertAdjacentHTML('beforeend',` <button class="inline-art-open" type="button" data-art-open="${lessonChapter(l)}">${t('Explore the illustration ↗','探索插畫 ↗')}</button>`);main.querySelector('.keypoints').outerHTML=takeawayDeck(l);initDecision(l);main.querySelectorAll('.recall-card').forEach(b=>b.onclick=()=>{const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',open);b.querySelector('.recall-answer').hidden=!open;b.querySelector('.recall-prompt').textContent=open?t('Hide this idea ↙','收起要點 ↙'):t('Reveal an idea ↗','揭示要點 ↗');});header.querySelector('.lesson-meta').insertAdjacentHTML('afterend',`<nav class="lesson-waypoints" aria-label="${t('On this page','本頁內容')}"><button data-waypoint=".decision-room">${t('Choose','選擇')}</button><button data-waypoint=".case-study">${t('Explore the case','探索案例')}</button><button data-waypoint=".quiz">${t('Check yourself','自我測試')}</button><button data-waypoint=".reflection-journal">${t('Reflect','反思')}</button></nav>`);main.querySelectorAll('[data-waypoint]').forEach(b=>b.onclick=()=>{const target=main.querySelector(b.dataset.waypoint);target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});});}
function enhanceVisualHome(){main.querySelector('.progress-panel').insertAdjacentHTML('afterend',chapterPreview());const index=main.querySelector('.hero-index');index.innerHTML=artImage('chapter-7','hero-art',false)+`<div class="hero-art-tag">${t('A world of games, science & markets','遊戲、科學與市場的世界')}</div>`;main.querySelector('.hero .actions').insertAdjacentHTML('beforeend',`<button class="btn surprise-btn" type="button" id="surprise-lesson">${t('Pick a lesson for me ↗','幫我選一課 ↗')}</button>`);document.getElementById('surprise-lesson').onclick=()=>{const unread=DATA.lessons.filter(l=>!state.done.includes(l.id)),pool=unread.length?unread:DATA.lessons;location.hash='lesson/'+pool[Math.floor(Math.random()*pool.length)].id;};}
function enhanceVisualPage(h){if(h==='library'||h==='saved')main.querySelector('.page-heading').insertAdjacentHTML('afterend',artFigure(h==='saved'?'chapter-16':'chapter-15','page-visual',false));if(h==='about')main.querySelector('.about h1').insertAdjacentHTML('afterend',artFigure('chapter-3','page-visual',false));if(h==='lab')main.querySelector('h1').insertAdjacentHTML('afterend',artFigure('chapter-12','page-visual',false));}
